2019-11-06 08:31:59.818 [error] <0.537.0> CRASH REPORT Process <0.537.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"purpose">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.819 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.819 [error] <0.535.0> CRASH REPORT Process <0.535.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_met...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.537.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.536.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"purpose">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.535.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.499.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_met...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.498.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:34:48.776 [error] <0.513.0> CRASH REPORT Process <0.513.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:34:48.800 [error] <0.513.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.509.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:00.674 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:00.675 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.522.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:07.847 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:07.847 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.543.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:47.236 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.RailwayUiWeb.ConsumedMessageController',reason => nil},[{'Elixir.RailwayUiWeb.ConsumedMessageController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.RailwayUiWeb.Endpoint',plug_builder_call,2,[{file,"lib/railway_ui_web/endpoint.ex"},{line,1}]},{'Elixir.RailwayUiWeb.Endpoint','call (overridable 3)',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:47.237 [error] <0.577.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.575.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.RailwayUiWeb.ConsumedMessageController',reason => nil},[{'Elixir.RailwayUiWeb.ConsumedMessageController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.RailwayUiWeb.Endpoint',plug_builder_call,2,[{file,"lib/railway_ui_web/endpoint.ex"},{line,1}]},{'Elixir.RailwayUiWeb.Endpoint','call (overridable 3)',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:11.768 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:11.768 [error] <0.590.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.589.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:34.611 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:34.612 [error] <0.617.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:38.424 [error] <0.638.0> CRASH REPORT Process <0.638.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:38.425 [error] <0.638.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:47.193 [error] <0.648.0> CRASH REPORT Process <0.648.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:47.193 [error] <0.648.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.646.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:53.603 [error] <0.667.0> CRASH REPORT Process <0.667.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:53.604 [error] <0.667.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.660.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:24.558 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:24.580 [error] <0.525.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.523.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:32.335 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:32.336 [error] <0.533.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.532.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:36.326 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:36.340 [error] <0.649.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.648.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:40.275 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:40.275 [error] <0.664.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.648.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:56.124 [error] <0.674.0> CRASH REPORT Process <0.674.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => get_consumed_messages,message => nil,module => nil,reason => nil},[{nil,get_consumed_messages,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,1}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:56.124 [error] <0.674.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.673.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => get_consumed_messages,message => nil,module => nil,reason => nil},[{nil,get_consumed_messages,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,1}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:45:39.304 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_messages_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_messages_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:45:39.304 [error] <0.753.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.751.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_messages_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_messages_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:25.000 [error] <0.790.0> CRASH REPORT Process <0.790.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:25.010 [error] <0.790.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.789.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:32.811 [error] <0.811.0> CRASH REPORT Process <0.811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:32.812 [error] <0.811.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.810.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:33.670 [error] <0.830.0> CRASH REPORT Process <0.830.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:33.672 [error] <0.830.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.810.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-12 08:42:53.761 [error] <0.49.0> Loading of /Users/sophie.debenedetto/Dev/railway_hex/railway_ui/_build/test/lib/jason/ebin/Elixir.JASON.beam failed: badfile
2019-11-12 08:42:53.761 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.JASON':
  BEAM file exists but it defines a module named Elixir.Jason

